### ISSUE TITLE
add contentTypes for Nutil Web, Web Ilastik and Web Align

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_instances#10]
(tools are in dev and not yet registered in KG)

**ContentType schema:** 
+ https://humanbrainproject.github.io/openMINDS/v3/ **--> select** core/DATA/ContentType
+ https://github.com/HumanBrainProject/openMINDS_core/blob/v3/schemas/data/contentType.schema.tpl.json

**required property:** name
**recommended property:** extension, as well as description AND/OR link to specification

**Missing contentTypes (suggested names):**
+ ???

**Comment by Tomaz-Vieira** [comment]
> @Tomaz-Vieira that means we should probably should have sticked to `image_vnd.ilastik+x-hdf` instead of using a generic image hdf5 `image_x-hdf` since the combination of image + feature table is very specific to ilastik?

We need both the generic and the ilasik-specific formats. The `hdf5` files used for **input** in ilastik are just generic images. But the `hdf5` outputs produced by ilastik have special semantics , one of them being that special "features table". I would say that the "image cutouts" that I mentioned in the previous comment are still a part of the feature table: it is one cutout per line, and their meaning is very tied to the whole concept of the feature table.

**Comment by lzehl** [comment]
@Tomaz-Vieira thanks for the quick reply. I will add the missing content type for the specific ilastik hdf5 asap.

**Comment by UlrikeS91** [comment]
I'm closing this issue since I split it up into two to be able to keep track of the parts and also to summaries to status for each of them better.
