### ISSUE TITLE
only trigger openMINDS_upstream action if changes are pushed to main branch?

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_instances#165]
Suggestion to only trigger the openMINDS_upstream action if pushes occur on the main branch.

At the moment, the action is triggered for pushes to any branch

https://github.com/openMetadataInitiative/openMINDS_instances/blob/main/.github/workflows/openMINDS_upstream.yml

@lzehl @olinux @apdavison

**Comment by lzehl** [comment]
good catch. I agree we should update this
