### ISSUE TITLE
v3.0 multivariateAnalysis.jsonld

### ISSUE THREAD

**Issue by Raphael-Gazzotti** [openMetadataInitiative/openMINDS_instances#183]
The instance multivariateAnalysis.jsonld is located at "instances/v3.0/terminologie/analysisTechnique/" shouln't it be located in "instances/v3.0/terminologies/analysisTechnique/"?

terminologie -> terminologies

**Comment by lzehl** [comment]
@Raphael-Gazzotti yes: there should be no `terminology` folder only `terminologies`
