### ISSUE TITLE
MRI scanner (superclass) add children

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_instances#19]
There are (at least) the following MRI scanner types: 
- closed-bore MRI scanner
  - standard-bore MRI scanner
  - wide-bore MRI scanner
- open-bore MRI scanner

**Comment by UlrikeS91** [comment]
Should these types be added to any specific terminology? I can do this, but I'm not sure where they should go. DeviceType?

**Comment by lzehl** [comment]
Yes they should go into DeviceType, which currently only holds the superclass. @UlrikeS91 thanks for taking this over
