### ISSUE TITLE
new techniques: quantitative susceptibility mapping, susceptibility weighted imaging

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_instances#20]
quantitative susceptibility mapping
- synonyms: QSM
- definition: cf. https://en.wikipedia.org/wiki/Quantitative_susceptibility_mapping

susceptibility weighted imaging
- synonyms: SWI, BOLD venographic imaging (?)
- definition: cf. https://en.wikipedia.org/wiki/Susceptibility_weighted_imaging
- used with fully flow compensated, long echo, gradient recalled echo (GRE) pulse sequence

**Comment by spieschnik** [comment]
#473: pull request for quantitative susceptibility mapping

**Comment by spieschnik** [comment]
part of #25

**Comment by lzehl** [comment]
solved
