### ISSUE TITLE
subdirectory of graphStructures

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_instances#3]
@openMetadataInitiative/openminds-developers 

I would like to discuss and agree with all of you on a sub-directory structure for the controlled graphStructures we currently maintain in openMINDS (brain atlases and common coordinate spaces).

Currently the sub-directory is structured in the following way (OPTION NOW):
- **graphStructures/**
  - **brainAtlases/**
    - **»BA«/** (naming convention: BA abbreviation)
      - **»BA«.jsonld** (naming convention: BA abbreviation)
      - **parcellationEntities/**
        - **»PE«.jsonld** (naming convention: PE lookuplabel)
      - **versions/**
        - **»BAV«/** (naming convention: BAV atID basename)
          - **»BAV«.jsonld** (naming convention: BAV atID basename)
          - **parcellationEntities_»BAV«/** (naming convention: BAV atID basename)
            - **»PEV«.jsonld** (naming convention: PEV lookuplabel)
  - **commonCoordinateSpaces/**
    - **»CCS«/** (naming convention: CCS atID basename)
      - **»CCS«.jsonld** (naming convention: CCS atID basename)
      - **versions/**
        - **»CCSV«.jsonld** (naming convention: CCSV atID basename)

Despite the fact that the naming convention could be harmonized to be always the atID basename, this structure seems way to complex to me. Especially when we auto build from this the Read-The-Docs documentation of the controlled instances. I would like to discuss therefore if one of the following structure seems easier/more intuitive to you (feel also free to suggest a structure).

OPTION A (flat without "graphStructures" folder):
- **brainAtlases/**
  - **»BA«.jsonld** (naming convention: BA atID basename)
- **brainAtlasVersions/**
  - **»BAV«.jsonld** (naming convention: BAV atID basename)
- **parcellationEntities/**
  - **»PE«.jsonld** (naming convention: PE atID basename)
- **parcellationEntityVersions/**
  - **»PEV«.jsonld** (naming convention: PEV atID basename)
- **commonCoordinateSpaces/**
  - **»CCS«.jsonld** (naming convention: CCS atID basename)
- **commonCoordinateSpaceVersions/**
  - **»CCSV«.jsonld** (naming convention: CCSV atID basename)

OPTION B:
- **graphStructures/**
  - **brainAtlases/**
    - **»BA«.jsonld** (naming convention: BA atID basename)
    - **brainAtlasVersions/**
      - **»BA«/** (naming convention: BA atID basename)
        - **»BAV«.jsonld** (naming convention: BAV atID basename)
    - **parcellationEntities/**
      - **»BA«/** (naming convention: BA atID basename)
        - **»PE«.jsonld** (naming convention: PE atID basename)
    - **parcellationEntityVersions/**
      - **»BAV«/** (naming convention: BAV atID basename)
        - **»PEV«.jsonld** (naming convention: PEV atID basename)
  - **commonCoordinateSpaces/**
    - **»CCS«.jsonld** (naming convention: CCS atID basename)
    - **commonCoordinateSpaceVersions/**
      - **»CCS«/** (naming convention: CCS atID basename)
        - **»CCSV«.jsonld** (naming convention: CCSV atID basename)

OPTION C:
- **graphStructures/**
  - **brainAtlases/**
    - **»BA«/** (naming convention: BA atID basename)
      - **»BA«.jsonld** (naming convention: BA atID basename)
      - **brainAtlasVersions/**
        - **»BAV«.jsonld** (naming convention: BAV atID basename)
      - **parcellationEntities/**
        - **»PE«.jsonld** (naming convention: PE atID basename)
      - **parcellationEntityVersions/**
        - **»BAV«/** (naming convention: BAV atID basename)
          - **»PEV«.jsonld** (naming convention: PEV atID basename)
  - **commonCoordinateSpaces/**
    - **»CCS«/** (naming convention: CCS atID basename)
      - **»CCS«.jsonld** (naming convention: CCS atID basename)
      - **commonCoordinateSpaceVersions/**
        - **»CCSV«.jsonld** (naming convention: CCSV atID basename)

OPTION D (flat with additional grouping where helpful):
- **brainAtlases/**
  - **»BA«.jsonld** (naming convention: BA atID basename)
- **brainAtlasVersions/**
  - **»BA«/** (naming convention: BA atID basename)
    - **»BAV«.jsonld** (naming convention: BAV atID basename)
- **parcellationEntities/**
  - **»BA«/** (naming convention: BA atID basename)
    - **»PE«.jsonld** (naming convention: PE atID basename)
- **parcellationEntityVersions/**
  - **»BAV«/** (naming convention: BAV atID basename)
    - **»PEV«.jsonld** (naming convention: PEV atID basename)
- **commonCoordinateSpaces/**
  - **»CCS«.jsonld** (naming convention: CCS atID basename)
- **commonCoordinateSpaceVersions/**
  - **»CCS«/** (naming convention: CCS atID basename)
    - **»CCSV«.jsonld** (naming convention: CCSV atID basename)

Note: PEs and PEVs have across atlases several thousand items.

**Comment by lzehl** [comment]
@aeidi89 what do you think about OPTION D ?

**Comment by aeidi89** [comment]
@lzehl I like OPTION D, it's flat but logical, especially considering the versions where most of the entities goes.
Regarding "graphStructures" as a main folder, I think the benefit would be that it signals that there are several dependencies for all the entities within. So if there are no big cons with adding a main folder, then why not.
