### ISSUE TITLE
Product accessibility options

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_instances#40]
I'm working on registering Paxinos and Watson's rat atlas at the moment and need to enter something under "accessibility" of the BrainAtlasVersion, but none of our existing options fit the book.  

[Existing terms](https://github.com/openMetadataInitiative/openMINDS_instances/tree/main/instances/latest/terminologies/productAccessibility):
1. controlled access (definition: With 'controlled access' selected, data and metadata are both released, but data are only available for users after they logged in and authenticated themselves.)
2. free access (definition: With 'free access' selected, data and metadata are both released and become immediately available without any access restrictions.)
3. restricted access (definition: With 'restricted access' selected, metadata are released, but data remain on an access restricted server.)
4. under embargo (definition: With 'under embargo' selected, metadata are released, but data remain unavailable for the public until the embargo is lifted.)

The problem is that the atlas is accessible to a user after purchase, but once purchased they can access the content freely. I don't know what should be done here.

**Comment by apdavison** [comment]
I would suggest "paid access", and we modify the "controlled access" definition to include "without payment".

**Comment by UlrikeS91** [comment]
I like this suggestion! I can prepare a PR in hope that others will agree, @lzehl 😉

**Comment by lzehl** [comment]
@UlrikeS91 @apdavison sounds good
