### ISSUE TITLE
Migrate and add ilastik ContentTypes

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_instances#52]
This is the other half of the original issue #10.

After reading the original issue, I think the following summary should be correct:

Together with @Tomaz-Vieira, @lzehl concluded that these content types are needed for both webilastik and ilastik (see comment https://github.com/openMetadataInitiative/openMINDS_instances/issues/10#issuecomment-1828120191):

**ilastik:**
application/vnd.ilastik.project+hdf5 (input/output)
image/png (input/output)
image/jpeg (input/output)
image/tiff (input/output)
any hdf5 images (input)
any n5 images (input)
image/vnd.ilastik+hdf5 (input/output)
application/vnd.ilastik.object-features+hdf5 (input/output)
application/vnd.ilastik.object-features+csv (input/output)
image/vnd.ilastik.pixelclassification+hdf5 (input/output)

**webilastik:**
application/vnd.ilastik.project+hdf5 (input/output)
image/png (input/output)
image/jpeg (input/output)
image/tiff (input/output)
any n5 images (input)
image/vnd.ilastik.pixelclassification+n5 (input/output)
image/vnd.ilastik.pixelclassification+neuroglancer.precomputed (input/output)
image/vnd.ilastik.segmentation+dzi (input/output)
image/vnd.ilastik.segmentation+dzip (input/output)
image/vnd.ilastik.segmentation+n5 (input/output)
image/vnd.ilastik.segmentation+neuroglancer.precomputed (input/output)

A few of these already exist (both in the old and new repo):
[image/png](https://github.com/openMetadataInitiative/openMINDS_instances/blob/main/instances/latest/contentTypes/image_png.jsonld)
[image/jpeg](https://github.com/openMetadataInitiative/openMINDS_instances/blob/main/instances/latest/contentTypes/image_jpeg.jsonld)
[image/tiff](https://github.com/openMetadataInitiative/openMINDS_instances/blob/main/instances/latest/contentTypes/image_tiff.jsonld)

And some were added to the [openMINDS core repository](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes) when we still collected the instances in the repository where the corresponding schema is deposited (see https://github.com/openMetadataInitiative/openMINDS_core/pull/489):
[image/vnd.ilastik.pixelclassification+hdf5](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.pixelclassification%2Bhdf5.jsonld)
[image/vnd.ilastik.pixelclassification+n5](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.pixelclassification%2Bn5.jsonld)
[image/vnd.ilastik.pixelclassification+neuroglancer.precomputed](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.pixelclassification%2Bneuroglancer.precomputed.jsonld)
[image/vnd.ilastik.segmentation+dzi](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.segmentation%2Bdzi.jsonld)
[image/vnd.ilastik.segmentation+dzip](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.segmentation%2Bdzip.jsonld)
[image/vnd.ilastik.segmentation+n5](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.segmentation%2Bn5.jsonld)
[image/vnd.ilastik.segmentation+neuroglancer.precomputed](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_vnd.ilastik.segmentation%2Bneuroglancer.precomputed) (This one also has a typo in the file name and does not end on ".jsonld")
[image/x-hdf](https://github.com/openMetadataInitiative/openMINDS_core/blob/v4/instances/data/contentTypes/image_x-hdf.jsonld)

I could not find the content type for:
- any n5 images: Maybe I just couldn't find it? 
- image/vnd.ilastik+hdf5: This was discussed in the issue and concluded that it should also be added, but wasn't done in the end. 

In any case, none of the ilastik content types have been migrated to the new repository [openMINDS_instances](https://github.com/openMetadataInitiative/openMINDS_instances/tree/main/instances/latest/contentTypes).

I guess we should migrate them to the new repo and add the missing ones? I can prepare the PR but I would like to get the OK from @lzehl that this summary is correct.

**Comment by lzehl** [comment]
@UlrikeS91 content types like licenses are currently not synchronized in EBRAINS because the cleanup was not finalized yet. So you can move them, but follow the new naming convention for content types (in case they do not yet follow this):

filename: atid basename + `".jsonld"`
atid basename: name with `"/"` replaced with `"_"`
name: IANA.org based naming convention
description: short description of the content type incl main format it is based on (if no specification is added; if you don't know and need to investigate we can postpone this to a later point in time; for new content types I want to make this a rule)
