### ISSUE TITLE
Add content types for Models

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_instances#7]
Some more content types I came across while migrating Models to KGv3

Stan (https://mc-stan.org/)
TVB
BlueNaaS
DPSNN
GROMACS
PLUMED

**Comment by UlrikeS91** [comment]
I'll try to add some of them, but I'm not sure all will be equally easy. I will summarize my findings in this issue first for each one and then we can decide.

**Stan**
Resources:
- https://mc-stan.org/ (webpage)
- https://search.kg.ebrains.eu/instances/615edae7-2697-49cf-b730-5b02bb652969 (KG model)
- 
Info:
- "platform for statistical modeling and high-performance statistical computation"
- accessed through different interfaces: Command-line, R, Python (https://mc-stan.org/users/documentation/)
- at least for R, users are recommended to save their model files as ".stan" (as far as I understand, those are still "just" normal R scripts; https://mc-stan.org/docs/2_19/stan-users-guide/file-extensions.html)
- 
Instances:
We could add the .stan as "application_vnd.stan.R" or "application_vnd.R.stand". I couldn't find much information about the others. Also, it seems to me that the KG model is just mentioning this as an option for running the model. How would this even be linked on the model?

**Comment by UlrikeS91** [comment]
**TVB**
Resources:
- https://www.thevirtualbrain.org/tvb/zwei/ (webpage)
- https://www.thevirtualbrain.org/tvb/zwei/brainsimulator-data (file format specifications for input and output)
- https://search.kg.ebrains.eu/instances/615edae7-2697-49cf-b730-5b02bb652969 (KG model, same as above)

Info:
- import: "TVB projects or single data types: TVB's own ZIP/HDF5 format"
- export: 
  - data: 
    - internally stored: HDF5 
    - export entire project: zip (contains folder structure following data types of TVB software, xml file as guide for folder structure, hdf5 files for each data type)
    - export individual HDF5 files
  - simulation config:
    - export config setup as JSON 
  - visualizer graphics (from TVB's visualizers):
    - download images as PNG    
    - some visualizers are built with vector graphics - export SVG from those
    
Instances:
- application_vnd.TVB+zip
- application_vnd.TVB+xml
- application_vnd.TVB.simulation+json
- maybe:
  - application_vnd.TVB+hdf5 
  - application_vnd.TVB.visualizer+png
  - application_vnd.TVB.visualizer+svg
I'm not sure if the hdf5, png and svg are special for the TVB software. hdf5 is very possible, bt I doubt if for png or svg.

**Comment by UlrikeS91** [comment]
@apdavison and @lzehl, could you please have a look at the linked issues (#67 - #72) and let me know what to do. I'm not that familiar with content types yet and will need some guidance in the beginning. 

PS: I'm closing this issue since I split it into 6 issue - one for each of them.
